package repository

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"gorm.io/gorm"

	domain "duluin_invoice/app/domain/journal"
	"duluin_invoice/app/model"
	"duluin_invoice/utils"
)

// journalListColumns — fields the MasterTable may show / sort by.
var journalListColumns = []string{
	"number", "date", "description", "status", "total_debit", "total_credit", "created_at",
}

type JournalRepository struct{ db *gorm.DB }

func NewJournalRepository(db *gorm.DB) domain.IRepository { return &JournalRepository{db: db} }

func (r *JournalRepository) Create(dto *domain.CreateDTO, actorID string) (*model.JournalEntry, error) {
	date, err := parseJournalDate(dto.Date)
	if err != nil {
		return nil, err
	}

	number := strings.TrimSpace(dto.Number)
	if number != "" {
		if exists, err := r.numberExists(dto.CompanyID, number, ""); err != nil {
			return nil, err
		} else if exists {
			return nil, &domain.ErrNumberExists{Number: number}
		}
	}

	key := strings.TrimSpace(dto.IdempotencyKey)
	var entryID string

	err = r.db.Transaction(func(tx *gorm.DB) error {
		if key != "" {
			if existing, err := findByIdempotencyKeyTx(tx, dto.CompanyID, key); err != nil {
				return err
			} else if existing != nil {
				entryID = existing.ID
				return nil
			}
		}

		n := number
		if n == "" {
			gen, err := generateJournalEntryNumber(tx, dto.CompanyID, dto.JournalBookID, date)
			if err != nil {
				return err
			}
			n = gen
		}

		entry := &model.JournalEntry{
			ID:             uuid.NewString(),
			CompanyID:      dto.CompanyID,
			JournalBookID:  dto.JournalBookID,
			Number:         n,
			Description:    strings.TrimSpace(dto.Description),
			Date:           date,
			IdempotencyKey: key,
			CreatedBy:      actorID,
			UpdatedBy:      actorID,
		}
		lines, totalDebit, totalCredit := buildJournalLines(dto.Lines, dto.CompanyID, entry.ID)
		entry.TotalDebit, entry.TotalCredit = totalDebit, totalCredit

		if err := tx.Create(entry).Error; err != nil {
			// A race: two concurrent requests with the same idempotency key
			// both passed the check above. The unique index catches it —
			// re-fetch and treat this as the idempotent replay.
			if key != "" && isUniqueViolation(err) {
				if existing, ferr := findByIdempotencyKeyTx(tx, dto.CompanyID, key); ferr == nil && existing != nil {
					entryID = existing.ID
					return nil
				}
			}
			return fmt.Errorf("create journal entry: %w", err)
		}
		if err := tx.Create(&lines).Error; err != nil {
			return fmt.Errorf("create journal lines: %w", err)
		}
		entryID = entry.ID
		return nil
	})
	if err != nil {
		return nil, err
	}
	return r.FindByID(dto.CompanyID, entryID)
}

func (r *JournalRepository) Update(companyID, id string, dto *domain.UpdateDTO, actorID string) (*model.JournalEntry, error) {
	existing, err := r.FindByID(companyID, id)
	if err != nil {
		return nil, err
	}

	date, err := parseJournalDate(dto.Date)
	if err != nil {
		return nil, err
	}

	number := strings.TrimSpace(dto.Number)
	bookChanged := dto.JournalBookID != "" && dto.JournalBookID != existing.JournalBookID
	periodChanged := date.Year() != existing.Date.Year() || date.Month() != existing.Date.Month()
	looksAutoGenerated := number == "" || strings.HasPrefix(strings.ToUpper(number), "JE-")

	err = r.db.Transaction(func(tx *gorm.DB) error {
		n := number
		if (bookChanged || periodChanged) && looksAutoGenerated {
			gen, genErr := generateJournalEntryNumber(tx, companyID, dto.JournalBookID, date)
			if genErr != nil {
				return genErr
			}
			n = gen
		}
		if n == "" {
			n = existing.Number
		}
		if !strings.EqualFold(n, existing.Number) {
			if exists, err := r.numberExists(companyID, n, id); err != nil {
				return err
			} else if exists {
				return &domain.ErrNumberExists{Number: n}
			}
		}

		lines, totalDebit, totalCredit := buildJournalLines(dto.Lines, companyID, id)

		updates := map[string]any{
			"journal_book_id": dto.JournalBookID,
			"number":          n,
			"description":     strings.TrimSpace(dto.Description),
			"date":            date,
			"total_debit":     totalDebit,
			"total_credit":    totalCredit,
			"updated_at":      time.Now(),
			"updated_by":      actorID,
		}
		if err := tx.Model(&model.JournalEntry{}).
			Where("id = ? AND company_id = ?", id, companyID).Updates(updates).Error; err != nil {
			return fmt.Errorf("update journal entry %s: %w", id, err)
		}
		if err := tx.Where("journal_entry_id = ?", id).Delete(&model.JournalLine{}).Error; err != nil {
			return fmt.Errorf("clear journal lines %s: %w", id, err)
		}
		if err := tx.Create(&lines).Error; err != nil {
			return fmt.Errorf("create journal lines %s: %w", id, err)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return r.FindByID(companyID, id)
}

func (r *JournalRepository) FindByID(companyID, id string) (*model.JournalEntry, error) {
	var e model.JournalEntry
	err := r.db.
		Preload("Lines", func(db *gorm.DB) *gorm.DB { return db.Order("line_order ASC") }).
		Where("id = ? AND company_id = ?", id, companyID).First(&e).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, &domain.ErrNotFound{ID: id}
	}
	if err != nil {
		return nil, fmt.Errorf("find journal entry %s: %w", id, err)
	}
	return &e, nil
}

func (r *JournalRepository) FindByIdempotencyKey(companyID, key string) (*model.JournalEntry, error) {
	return findByIdempotencyKeyTx(r.db, companyID, key)
}

func findByIdempotencyKeyTx(tx *gorm.DB, companyID, key string) (*model.JournalEntry, error) {
	if strings.TrimSpace(key) == "" {
		return nil, nil
	}
	var e model.JournalEntry
	err := tx.Where("company_id = ? AND idempotency_key = ?", companyID, key).First(&e).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("find journal entry by idempotency key: %w", err)
	}
	return &e, nil
}

// FindAll — the journal list, paginated + sortable like every other master
// list (lines aren't included; the FE reads TotalDebit/TotalCredit).
func (r *JournalRepository) FindAll(f *domain.Filter) (*utils.OffsetPaginationResult, error) {
	q := r.db.Model(&model.JournalEntry{}).Where("company_id = ?", f.CompanyID)
	if s := strings.TrimSpace(f.Search); s != "" {
		like := "%" + strings.ToLower(s) + "%"
		q = q.Where("lower(number) LIKE ? OR lower(description) LIKE ?", like, like)
	}
	if f.JournalBookID != "" {
		q = q.Where("journal_book_id = ?", f.JournalBookID)
	}
	if f.Status != "" {
		q = q.Where("status = ?", f.Status)
	}

	sortCol := utils.NormalizeSort(f.Sort, journalListColumns, "date")
	order := f.Order
	if strings.TrimSpace(order) == "" {
		order = "DESC"
	}
	return utils.GetPaginatedDataOffset(q, utils.OffsetPaginationOptions{
		Model:                &model.JournalEntry{},
		Page:                 f.Page,
		Limit:                f.PageSize,
		Sort:                 sortCol,
		Order:                order,
		Select:               f.Fields,
		ValidColumns:         journalListColumns,
		PreserveAssociations: true,
	})
}

func (r *JournalRepository) Delete(companyID, id string) error {
	if _, err := r.FindByID(companyID, id); err != nil {
		return err
	}
	return r.db.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("journal_entry_id = ?", id).Delete(&model.JournalLine{}).Error; err != nil {
			return fmt.Errorf("delete journal lines %s: %w", id, err)
		}
		if err := tx.Where("id = ? AND company_id = ?", id, companyID).Delete(&model.JournalEntry{}).Error; err != nil {
			return fmt.Errorf("delete journal entry %s: %w", id, err)
		}
		return nil
	})
}

func (r *JournalRepository) SetStatus(companyID, id, actorID string, status model.JournalEntryStatus) error {
	res := r.db.Model(&model.JournalEntry{}).Where("id = ? AND company_id = ?", id, companyID).
		Updates(map[string]any{"status": status, "updated_at": time.Now(), "updated_by": actorID})
	if res.Error != nil {
		return fmt.Errorf("set journal entry status %s: %w", id, res.Error)
	}
	if res.RowsAffected == 0 {
		return &domain.ErrNotFound{ID: id}
	}
	return nil
}

// AccountsActive — accounting-engine-service parity: a journal line can't
// post against a deactivated COA account.
func (r *JournalRepository) AccountsActive(companyID string, accountIDs []string) (bool, error) {
	if len(accountIDs) == 0 {
		return true, nil
	}
	var n int64
	err := r.db.Model(&model.Account{}).
		Where("company_id = ? AND id IN ? AND is_active = ?", companyID, accountIDs, utils.BoolInt(true).ToInt()).
		Count(&n).Error
	if err != nil {
		return false, fmt.Errorf("check account status: %w", err)
	}
	return int(n) == len(accountIDs), nil
}

func (r *JournalRepository) numberExists(companyID, number, exceptID string) (bool, error) {
	q := r.db.Model(&model.JournalEntry{}).Where("company_id = ? AND lower(number) = lower(?)", companyID, number)
	if exceptID != "" {
		q = q.Where("id <> ?", exceptID)
	}
	var n int64
	if err := q.Count(&n).Error; err != nil {
		return false, fmt.Errorf("check journal number: %w", err)
	}
	return n > 0, nil
}

// generateJournalEntryNumber — ports accounting-engine-service's
// GenerateJournalEntryNumber/getNextSequence verbatim: JE-<BookCode>-<MMYYYY>-<NNN>,
// NNN = the highest existing trailing number for this company+prefix+period,
// plus one (not a naive count — safe against gaps from deletions).
func generateJournalEntryNumber(tx *gorm.DB, companyID, journalBookID string, date time.Time) (string, error) {
	var code string
	if err := tx.Model(&model.JournalBook{}).Where("id = ? AND company_id = ?", journalBookID, companyID).
		Pluck("code", &code).Error; err != nil || code == "" {
		code = "GJ"
	}
	code = strings.ToUpper(code)
	period := fmt.Sprintf("%02d%d", int(date.Month()), date.Year())
	prefix := fmt.Sprintf("JE-%s-%s-", code, period)

	var numbers []string
	if err := tx.Model(&model.JournalEntry{}).
		Where("company_id = ? AND number LIKE ?", companyID, prefix+"%").
		Pluck("number", &numbers).Error; err != nil {
		return "", fmt.Errorf("scan journal numbers: %w", err)
	}
	return fmt.Sprintf("%s%03d", prefix, nextSequence(numbers)), nil
}

// nextSequence — max trailing integer across refs, + 1.
func nextSequence(refs []string) int {
	max := 0
	for _, ref := range refs {
		parts := strings.Split(ref, "-")
		if len(parts) == 0 {
			continue
		}
		if seq, err := strconv.Atoi(parts[len(parts)-1]); err == nil && seq > max {
			max = seq
		}
	}
	return max + 1
}

func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

func buildJournalLines(dtos []domain.JournalLineDTO, companyID, entryID string) ([]model.JournalLine, float64, float64) {
	lines := make([]model.JournalLine, 0, len(dtos))
	var totalDebit, totalCredit float64
	for i, l := range dtos {
		lines = append(lines, model.JournalLine{
			ID:             uuid.NewString(),
			JournalEntryID: entryID,
			CompanyID:      companyID,
			AccountID:      l.AccountID,
			MitraID:        trimPtr(l.MitraID),
			Description:    strings.TrimSpace(l.Description),
			Debit:          l.Debit,
			Credit:         l.Credit,
			LineOrder:      i,
		})
		totalDebit += l.Debit
		totalCredit += l.Credit
	}
	return lines, totalDebit, totalCredit
}

func parseJournalDate(s string) (time.Time, error) {
	t, err := time.Parse("2006-01-02", strings.TrimSpace(s))
	if err != nil {
		return time.Time{}, &domain.ErrValidation{Message: "invalid date (format YYYY-MM-DD)"}
	}
	return t, nil
}
