version: "3.9"

services:
  duluin-invoicing-be:
    container_name: duluin-invoicing-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3903:3903"
    env_file:
      - ./src/.env
    # TAMBAHKAN INI:
    volumes:
      - ./src/.env:/app/.env
    restart: always
    networks:
      - duluin-network
      - apigateway_internal_network
      - hriscompanies_hris_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=invoicing-duluin"
        
networks:
  duluin-network:
    driver: bridge

  apigateway_internal_network:
    external: true
    name: apigateway_internal_network
  hriscompanies_hris_network:
    external: true
    name: hriscompanies_hris_network